services:

  postgres:
    image: postgis/postgis:16-3.4
    container_name: pyroclass-postgres
    environment:
      POSTGRES_DB: pyroclass
      POSTGRES_USER: pyroclass
      POSTGRES_PASSWORD: pyroclass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: pyroclass-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
    container_name: pyroclass-api
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/app/dataset
      - ./backend/ingestion:/app/ingestion
      - ./backend/ml:/app/ml
      - ./model_artifacts:/app/model_artifacts
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: