-- Migration 015: Add FIRMS ML feature columns
-- These columns store the pre-computed features from the FIRMS stage4 dataset,
-- enabling direct model inference without falling back to derivations.

ALTER TABLE hotspots
  ADD COLUMN IF NOT EXISTS scan                         FLOAT,
  ADD COLUMN IF NOT EXISTS track                        FLOAT,
  ADD COLUMN IF NOT EXISTS acq_hour                     INTEGER,
  ADD COLUMN IF NOT EXISTS thermal_difference           FLOAT,
  ADD COLUMN IF NOT EXISTS thermal_ratio                FLOAT,
  ADD COLUMN IF NOT EXISTS pixel_area                   FLOAT,
  ADD COLUMN IF NOT EXISTS frp_per_pixel_area           FLOAT,
  ADD COLUMN IF NOT EXISTS detections_7d                INTEGER,
  ADD COLUMN IF NOT EXISTS detections_30d               INTEGER,
  ADD COLUMN IF NOT EXISTS active_days_90d              FLOAT,
  ADD COLUMN IF NOT EXISTS active_day_ratio_90d         FLOAT,
  ADD COLUMN IF NOT EXISTS frp_mean_90d                 FLOAT,
  ADD COLUMN IF NOT EXISTS frp_ratio_to_90d_mean        FLOAT,
  ADD COLUMN IF NOT EXISTS time_since_previous_detection FLOAT,
  ADD COLUMN IF NOT EXISTS distance_to_refinery          FLOAT,
  ADD COLUMN IF NOT EXISTS refinery_within_1km           INTEGER,
  ADD COLUMN IF NOT EXISTS refinery_within_5km           INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_power_plant       FLOAT,
  ADD COLUMN IF NOT EXISTS power_plant_within_1km        INTEGER,
  ADD COLUMN IF NOT EXISTS power_plant_within_5km        INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_industrial_works  FLOAT,
  ADD COLUMN IF NOT EXISTS industrial_works_within_1km   INTEGER,
  ADD COLUMN IF NOT EXISTS industrial_works_within_5km   INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_industrial_area   FLOAT,
  ADD COLUMN IF NOT EXISTS industrial_area_within_1km    INTEGER,
  ADD COLUMN IF NOT EXISTS industrial_area_within_5km    INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_quarry            FLOAT,
  ADD COLUMN IF NOT EXISTS quarry_within_1km             INTEGER,
  ADD COLUMN IF NOT EXISTS quarry_within_5km             INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_mine              FLOAT,
  ADD COLUMN IF NOT EXISTS mine_within_1km               INTEGER,
  ADD COLUMN IF NOT EXISTS mine_within_5km               INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_nearest_industrial FLOAT,
  ADD COLUMN IF NOT EXISTS industrial_within_1km         INTEGER,
  ADD COLUMN IF NOT EXISTS industrial_within_5km         INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_forest            FLOAT,
  ADD COLUMN IF NOT EXISTS forest_within_1km             INTEGER,
  ADD COLUMN IF NOT EXISTS forest_within_5km             INTEGER,
  ADD COLUMN IF NOT EXISTS distance_to_farmland          FLOAT,
  ADD COLUMN IF NOT EXISTS farmland_within_1km           INTEGER,
  ADD COLUMN IF NOT EXISTS farmland_within_5km           INTEGER,
  ADD COLUMN IF NOT EXISTS label                         INTEGER,
  ADD COLUMN IF NOT EXISTS label_name                    TEXT;
